from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Tuple

from .pdf_parser_api_client import PDFParseAPIClient
from .platform_api_client import PlatformAPIClient
from .spu_generator_api_client import SPUGeneratorAPIClient
from .spu_review_validator import REVIEW_STATUS_AUTO_VALIDATED, validate_generated_spu
from .task_store import TaskStore
from .template_library import (
    TemplateLibrary,
    build_specbundle,
    build_spu_from_template,
    infer_template_query,
    render_markdown_from_spu,
)


def _utc_now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _choose_template_action(
    recommendations: List[Dict[str, Any]],
    *,
    template_strategy: str,
    template_id: str | None,
) -> Tuple[str, str]:
    if template_strategy in {"direct_use", "based_generate"}:
        selected = (template_id or (recommendations[0].get("templateId") if recommendations else "") or "").strip()
        return template_strategy, selected
    if template_strategy == "ignore":
        return "ignore", ""
    if not recommendations:
        return "ignore", ""
    top = recommendations[0]
    score = float(top.get("score") or 0.0)
    selected = str(top.get("templateId") or "")
    if score >= 0.95:
        return "direct_use", selected
    if score >= 0.80:
        return "based_generate", selected
    return "ignore", ""


def _build_template_spu_result(spu_obj: Dict[str, Any], *, confidence: float, action: str) -> Tuple[Dict[str, Any], bytes]:
    markdown = render_markdown_from_spu(spu_obj)
    bundle_bytes = build_specbundle(spu_obj, markdown)
    spu_result = {
        "taskId": f"spu_{action}",
        "status": "success",
        "spu": spu_obj,
        "markdown": markdown,
        "json": spu_obj,
        "confidence": confidence,
        "reviewPoints": [f"Generated by template action: {action}"],
        "downloadUrl": "",
    }
    return spu_result, bundle_bytes


def _recommendation_score(recommendations: List[Dict[str, Any]], template_id: str, default: float) -> float:
    for item in recommendations:
        if str(item.get("templateId") or "") == template_id:
            try:
                return float(item.get("score") or default)
            except Exception:
                return default
    try:
        return float(recommendations[0].get("score") or default)
    except Exception:
        return default


def translation_pipeline(
    task_id: str,
    pdf_path: str,
    standard_code: str,
    base_dir: Path,
    task_store: TaskStore,
    ocr_max_pages: int = 20,
    template_strategy: str = "auto",
    template_id: str | None = None,
) -> None:
    _ = ocr_max_pages

    try:
        parser_client = PDFParseAPIClient()
        latest_parse_id = ""

        def handle_parse_status(status_payload: dict) -> None:
            nonlocal latest_parse_id
            latest_parse_id = str(status_payload.get("parseId") or latest_parse_id or "")
            task_store.update_parse_state(
                task_id,
                parse_id=latest_parse_id,
                parse_status=str(status_payload.get("status") or "processing"),
                parse_progress=float(status_payload.get("progress", 0.0) or 0.0),
                parse_error=str(status_payload.get("error") or ""),
            )

        parse_result = parser_client.parse_pdf(
            pdf_path=pdf_path,
            standard_code=standard_code,
            options={
                "extractTables": True,
                "extractFormulas": True,
                "ocrLanguage": "chi_sim+eng",
            },
            on_status=handle_parse_status,
        )
        extracted_data = parse_result.get("extractedData", {}) or {}
        parse_validate_result = parser_client.validate_extracted_data(
            extracted_data=extracted_data,
            target_schema="SPU-v1",
        )

        template_library = TemplateLibrary(runtime_dir=base_dir / "runtime")
        template_query = infer_template_query(standard_code, extracted_data, spu=None)
        recommendations = template_library.find_similar_templates(template_query)
        task_store.update_template_state(
            task_id,
            template_query=template_query,
            template_recommendations=recommendations,
        )

        selected_action, selected_template_id = _choose_template_action(
            recommendations,
            template_strategy=template_strategy,
            template_id=template_id,
        )
        task_store.update_template_state(
            task_id,
            template_action=selected_action,
            template_selected_id=selected_template_id,
        )

        spu_client = SPUGeneratorAPIClient()
        spu_result: Dict[str, Any]
        bundle_bytes: bytes

        if selected_action in {"direct_use", "based_generate"} and selected_template_id:
            selected_template = template_library.get_template(selected_template_id)
            if selected_template and isinstance(selected_template.get("spu"), dict):
                template_spu = selected_template.get("spu", {})
                if selected_action == "direct_use":
                    spu_obj = template_spu
                    reuse_event = {
                        "eventType": "TEMPLATE_REUSED",
                        "taskId": task_id,
                        "templateId": selected_template_id,
                        "spuId": selected_template.get("spuId"),
                        "timestamp": _utc_now(),
                    }
                    template_library.increment_usage(selected_template_id)
                    template_library.log_event(reuse_event)
                    task_store.append_audit_event(task_id, reuse_event)
                    rec_score = _recommendation_score(recommendations, selected_template_id, 0.95)
                    spu_result, bundle_bytes = _build_template_spu_result(
                        spu_obj,
                        confidence=max(0.95, rec_score),
                        action=selected_action,
                    )
                else:
                    spu_obj = build_spu_from_template(
                        template_spu,
                        standard_code=standard_code,
                        extracted_data=extracted_data,
                    )
                    based_event = {
                        "eventType": "TEMPLATE_BASED_GENERATION",
                        "taskId": task_id,
                        "templateId": selected_template_id,
                        "spuId": selected_template.get("spuId"),
                        "timestamp": _utc_now(),
                    }
                    template_library.increment_usage(selected_template_id)
                    template_library.log_event(based_event)
                    task_store.append_audit_event(task_id, based_event)
                    rec_score = _recommendation_score(recommendations, selected_template_id, 0.88)
                    spu_result, bundle_bytes = _build_template_spu_result(
                        spu_obj,
                        confidence=max(0.88, rec_score),
                        action=selected_action,
                    )
            else:
                selected_action = "ignore"
                selected_template_id = ""
                spu_result = spu_client.generate_spu(
                    standard_code=standard_code,
                    extracted_data=extracted_data,
                )
                bundle_bytes = spu_client.download_specbundle(spu_result.get("downloadUrl", ""))
        else:
            if recommendations:
                skip_event = {
                    "eventType": "TEMPLATE_SKIPPED",
                    "taskId": task_id,
                    "templateId": recommendations[0].get("templateId"),
                    "spuId": recommendations[0].get("spuId"),
                    "timestamp": _utc_now(),
                }
                template_library.log_event(skip_event)
                task_store.append_audit_event(task_id, skip_event)

            spu_result = spu_client.generate_spu(
                standard_code=standard_code,
                extracted_data=extracted_data,
            )
            bundle_bytes = spu_client.download_specbundle(spu_result.get("downloadUrl", ""))

        spu_obj = spu_result.get("spu", {}) or {}
        spu_validate_result = spu_client.validate_spu(
            spu=spu_obj,
            target_schema="SPU-v1",
        )
        if not bool(spu_validate_result.get("valid", False)):
            raise RuntimeError("INVALID_SPU_SCHEMA")

        spu_confidence = float(spu_result.get("confidence", 0.0) or 0.0)
        review_result = validate_generated_spu(
            spu=spu_obj,
            extracted_data=extracted_data,
            confidence=spu_confidence,
            standard_code=standard_code,
        )
        review_status = str(review_result.get("reviewStatus") or "NEEDS_REVIEW")
        review_required = review_status != REVIEW_STATUS_AUTO_VALIDATED

        auto_registry = {
            "registered": False,
            "source": "generated",
            "verified": False,
            "reason": f"registration blocked by reviewStatus={review_status}",
        }
        if review_status == REVIEW_STATUS_AUTO_VALIDATED:
            platform_client = PlatformAPIClient()
            auto_registry = platform_client.register_generated_spu(
                spu=spu_obj,
                verified=True,
            )

        review_points: list[str] = []
        for issue in review_result.get("issues", []) or []:
            if isinstance(issue, dict):
                review_points.append(f"[{issue.get('level', 'warning')}] {issue.get('code', 'ISSUE')}: {issue.get('message', '')}")
            else:
                review_points.append(str(issue))
        for item in spu_result.get("reviewPoints", []) or []:
            review_points.append(str(item))
        if not bool(parse_validate_result.get("valid", True)):
            for error in parse_validate_result.get("errors", []) or []:
                review_points.append(f"PDF schema validation warning: {error}")

        task_store.mark_done(
            task_id=task_id,
            yaml_text=str(spu_result.get("markdown", "") or ""),
            result_markdown=str(spu_result.get("markdown", "") or ""),
            result_json=spu_result.get("json", {}) or {},
            result_spu=spu_obj,
            confidence=spu_confidence,
            review_points=review_points,
            parse_result=parse_result,
            validate_result=parse_validate_result,
            spu_result=spu_result,
            spu_validate_result=spu_validate_result,
            bundle_download_url=f"/download/{task_id}.specbundle",
            bundle_bytes=bundle_bytes,
            review_required=review_required,
            review_status=review_status,
            review_score=float(review_result.get("score", 0.0) or 0.0),
            review_passed=bool(review_result.get("passed", False)),
            review_issues=review_result.get("issues", []) or [],
            template_query=template_query,
            template_recommendations=recommendations,
            template_action=selected_action,
            template_selected_id=selected_template_id,
            auto_registry=auto_registry,
        )
    except Exception as exc:  # noqa: BLE001
        try:
            task_store.update_parse_state(
                task_id,
                parse_status="failed",
                parse_error=str(exc),
            )
        except Exception:
            pass
        task_store.mark_error(task_id=task_id, error=str(exc))
