import React from "react";
import ReactDOM from "react-dom/client";
import SPUApp from "./SPUApp";
import AIPatchCenter from "./AIPatchCenter";
import ConflictExplainability from "./ConflictExplainability";
import PropagationPreview from "./PropagationPreview";
import KnowledgeGraphExplorer from "./KnowledgeGraphExplorer";
import NormQAConsole from "./NormQAConsole";
import ComplianceDashboard from "./ComplianceDashboard";
import NormUpdateCenter from "./NormUpdateCenter";
import RuntimeEventCenter from "./RuntimeEventCenter";
import ProofViewer from "./ProofViewer";
import BIMMappingStudio from "./BIMMappingStudio";
import SensorBindingCenter from "./SensorBindingCenter";
import RuntimeTrustDashboard from "./RuntimeTrustDashboard";
import LiveRiskBoard from "./LiveRiskBoard";
import EngineeringCopilotConsole from "./EngineeringCopilotConsole";
import AutoRemediationCenter from "./AutoRemediationCenter";
import ProjectComplianceDashboard from "./ProjectComplianceDashboard";
import MobileBodyRuntime from "./MobileBodyRuntime";
import BIMRuntimeLinkagePage from "./BIMRuntimeLinkagePage";
import EngineeringSemanticTwinMode from "./EngineeringSemanticTwinMode";
import BodyCenter from "./BodyCenter";
import GateRuntimePanel from "./GateRuntimePanel";
import InputPipelineViewer from "./InputPipelineViewer";
import RuntimeTrace from "./RuntimeTrace";
import DependencyExplorer from "./DependencyExplorer";
import LiveComplianceBoard from "./LiveComplianceBoard";
import ConsistencyReport from "./ConsistencyReport";
import RuntimeSemanticExplorer from "./RuntimeSemanticExplorer";
import BodyTimeline from "./BodyTimeline";
import GateRuntimeTrace from "./GateRuntimeTrace";
import ProofChainViewer from "./ProofChainViewer";
import LiveConclusionBoard from "./LiveConclusionBoard";
import ReplayStudio from "./ReplayStudio";
import LiveRuntimeCenter from "./LiveRuntimeCenter";
import EngineeringReasoningPanel from "./EngineeringReasoningPanel";
import CausalExplorer from "./CausalExplorer";
import RuntimeAnomalyCenter from "./RuntimeAnomalyCenter";
import PredictiveRiskDashboard from "./PredictiveRiskDashboard";
import RuntimeMemoryExplorer from "./RuntimeMemoryExplorer";
import RemediationPlanner from "./RemediationPlanner";
import ProjectSemanticBrainDashboard from "./ProjectSemanticBrainDashboard";
import CopilotWorkspace from "./CopilotWorkspace";
import ComplianceIntelligenceCenter from "./ComplianceIntelligenceCenter";
import KnowledgeCompressionDashboard from "./KnowledgeCompressionDashboard";
import CrossProjectIntelligenceCenter from "./CrossProjectIntelligenceCenter";
import "./index.css";

const path = window.location.pathname.toLowerCase();
const isEngineeringSemanticTwinMode = path === "/" || path.endsWith("/engineering-semantic-twin") || path === "/engineering-semantic-twin";
const isAIPatchCenter = path.endsWith("/ai-patch-center") || path === "/ai-patch-center";
const isConflictExplainability = path.endsWith("/conflict-explainability") || path === "/conflict-explainability";
const isPropagationPreview = path.endsWith("/propagation-preview") || path === "/propagation-preview";
const isKnowledgeGraphExplorer = path.endsWith("/knowledge-graph-explorer") || path === "/knowledge-graph-explorer";
const isNormQAConsole = path.endsWith("/norm-qa-console") || path === "/norm-qa-console";
const isComplianceDashboard = path.endsWith("/compliance-dashboard") || path === "/compliance-dashboard";
const isNormUpdateCenter = path.endsWith("/norm-update-center") || path === "/norm-update-center";
const isRuntimeEventCenter = path.endsWith("/runtime-event-center") || path === "/runtime-event-center";
const isProofViewer = path.endsWith("/proof-viewer") || path === "/proof-viewer";
const isBimMappingStudio = path.endsWith("/bim-mapping-studio") || path === "/bim-mapping-studio";
const isSensorBindingCenter = path.endsWith("/sensor-binding-center") || path === "/sensor-binding-center";
const isRuntimeTrustDashboard = path.endsWith("/runtime-trust-dashboard") || path === "/runtime-trust-dashboard" || path.endsWith("/trust-dashboard") || path === "/trust-dashboard";
const isLiveRiskBoard = path.endsWith("/live-risk-board") || path === "/live-risk-board";
const isEngineeringCopilotConsole = path.endsWith("/engineering-copilot-console") || path === "/engineering-copilot-console";
const isAutoRemediationCenter = path.endsWith("/auto-remediation-center") || path === "/auto-remediation-center";
const isProjectComplianceDashboard = path.endsWith("/project-compliance-dashboard") || path === "/project-compliance-dashboard";
const isMobileBodyRuntime = path.endsWith("/mobile-body-runtime") || path === "/mobile-body-runtime";
const isBimRuntimeLinkage = path.endsWith("/bim-runtime-linkage") || path === "/bim-runtime-linkage";
const isBodyCenter = path.endsWith("/body-center") || path === "/body-center";
const isGateRuntimePanel = path.endsWith("/gate-runtime-panel") || path === "/gate-runtime-panel";
const isInputPipelineViewer = path.endsWith("/input-pipeline-viewer") || path === "/input-pipeline-viewer";
const isRuntimeTrace = path.endsWith("/runtime-trace") || path === "/runtime-trace";
const isDependencyExplorer = path.endsWith("/dependency-explorer") || path === "/dependency-explorer" || path.endsWith("/dependency-impact-viewer") || path === "/dependency-impact-viewer";
const isLiveComplianceBoard = path.endsWith("/live-compliance-board") || path === "/live-compliance-board";
const isConsistencyReport = path.endsWith("/consistency-report") || path === "/consistency-report" || path.endsWith("/semantic-consistency-report") || path === "/semantic-consistency-report";
const isRuntimeSemanticExplorer = path.endsWith("/runtime-semantic-explorer") || path === "/runtime-semantic-explorer";
const isBodyTimeline = path.endsWith("/body-timeline") || path === "/body-timeline";
const isGateRuntimeTrace = path.endsWith("/gate-runtime-trace") || path === "/gate-runtime-trace";
const isProofChainViewer = path.endsWith("/proof-chain-viewer") || path === "/proof-chain-viewer";
const isLiveConclusionBoard = path.endsWith("/live-conclusion-board") || path === "/live-conclusion-board";
const isReplayStudio = path.endsWith("/replay-studio") || path === "/replay-studio";
const isLiveRuntimeCenter = path.endsWith("/live-runtime-center") || path === "/live-runtime-center";
const isEngineeringReasoningPanel = path.endsWith("/engineering-reasoning-panel") || path === "/engineering-reasoning-panel";
const isCausalExplorer = path.endsWith("/causal-explorer") || path === "/causal-explorer";
const isRuntimeAnomalyCenter = path.endsWith("/runtime-anomaly-center") || path === "/runtime-anomaly-center";
const isPredictiveRiskDashboard = path.endsWith("/predictive-risk-dashboard") || path === "/predictive-risk-dashboard";
const isRuntimeMemoryExplorer = path.endsWith("/runtime-memory-explorer") || path === "/runtime-memory-explorer";
const isRemediationPlanner = path.endsWith("/remediation-planner") || path === "/remediation-planner";
const isProjectSemanticBrainDashboard = path.endsWith("/project-semantic-brain-dashboard") || path === "/project-semantic-brain-dashboard";
const isCopilotWorkspace = path.endsWith("/copilot-workspace") || path === "/copilot-workspace";
const isComplianceIntelligenceCenter = path.endsWith("/compliance-intelligence-center") || path === "/compliance-intelligence-center";
const isKnowledgeCompressionDashboard = path.endsWith("/knowledge-compression-dashboard") || path === "/knowledge-compression-dashboard";
const isCrossProjectIntelligenceCenter = path.endsWith("/cross-project-intelligence-center") || path === "/cross-project-intelligence-center";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    {isEngineeringSemanticTwinMode ? <EngineeringSemanticTwinMode /> : isAIPatchCenter ? <AIPatchCenter /> : isConflictExplainability ? <ConflictExplainability /> : isPropagationPreview ? <PropagationPreview /> : isKnowledgeGraphExplorer ? <KnowledgeGraphExplorer /> : isNormQAConsole ? <NormQAConsole /> : isComplianceDashboard ? <ComplianceDashboard /> : isNormUpdateCenter ? <NormUpdateCenter /> : isRuntimeEventCenter ? <RuntimeEventCenter /> : isProofViewer ? <ProofViewer /> : isBimMappingStudio ? <BIMMappingStudio /> : isSensorBindingCenter ? <SensorBindingCenter /> : isRuntimeTrustDashboard ? <RuntimeTrustDashboard /> : isLiveRiskBoard ? <LiveRiskBoard /> : isEngineeringCopilotConsole ? <EngineeringCopilotConsole /> : isAutoRemediationCenter ? <AutoRemediationCenter /> : isProjectComplianceDashboard ? <ProjectComplianceDashboard /> : isMobileBodyRuntime ? <MobileBodyRuntime /> : isBimRuntimeLinkage ? <BIMRuntimeLinkagePage /> : isBodyCenter ? <BodyCenter /> : isGateRuntimePanel ? <GateRuntimePanel /> : isInputPipelineViewer ? <InputPipelineViewer /> : isRuntimeTrace ? <RuntimeTrace /> : isDependencyExplorer ? <DependencyExplorer /> : isLiveComplianceBoard ? <LiveComplianceBoard /> : isConsistencyReport ? <ConsistencyReport /> : isRuntimeSemanticExplorer ? <RuntimeSemanticExplorer /> : isBodyTimeline ? <BodyTimeline /> : isGateRuntimeTrace ? <GateRuntimeTrace /> : isProofChainViewer ? <ProofChainViewer /> : isLiveConclusionBoard ? <LiveConclusionBoard /> : isReplayStudio ? <ReplayStudio /> : isLiveRuntimeCenter ? <LiveRuntimeCenter /> : isEngineeringReasoningPanel ? <EngineeringReasoningPanel /> : isCausalExplorer ? <CausalExplorer /> : isRuntimeAnomalyCenter ? <RuntimeAnomalyCenter /> : isPredictiveRiskDashboard ? <PredictiveRiskDashboard /> : isRuntimeMemoryExplorer ? <RuntimeMemoryExplorer /> : isRemediationPlanner ? <RemediationPlanner /> : isProjectSemanticBrainDashboard ? <ProjectSemanticBrainDashboard /> : isCopilotWorkspace ? <CopilotWorkspace /> : isComplianceIntelligenceCenter ? <ComplianceIntelligenceCenter /> : isKnowledgeCompressionDashboard ? <KnowledgeCompressionDashboard /> : isCrossProjectIntelligenceCenter ? <CrossProjectIntelligenceCenter /> : <SPUApp />}
  </React.StrictMode>
);
