export const AUDIT_EVENT = {
  SLOT_IMPORTED: "SLOT_IMPORTED",
  CONTAINER_CREATED: "CONTAINER_CREATED",
  SPU_BOUND: "SPU_BOUND",
  NODE_CREATED: "NODE_CREATED",
  FORM_SUBMITTED: "FORM_SUBMITTED",
  PATH_EXECUTED: "PATH_EXECUTED",
  RULES_EVALUATED: "RULES_EVALUATED",
  NODE_SIGNED: "NODE_SIGNED",
  NODE_FINALIZED: "NODE_FINALIZED",
  CONTAINER_STATE_CHANGED: "CONTAINER_STATE_CHANGED",
  CONTAINER_ARCHIVED: "CONTAINER_ARCHIVED",
} as const;

export type AuditEventType = (typeof AUDIT_EVENT)[keyof typeof AUDIT_EVENT];
